export const ModalItemsList = [
    "OPEN24HOUR",
    "HIGH24HOUR",
    "LOW24HOUR",
    "CHANGE24HOUR",
    "CHANGEPCT24HOUR",
    "CHANGEDAY",
    "CHANGEPCTDAY",
    "CHANGEHOUR",
    "CHANGEPCTHOUR"
];